repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.4
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]

  - repo: local
    hooks:
      - id: bump-version
        name: Bump patch version
        entry: .githooks/bump-version.sh
        language: script
        pass_filenames: false
        always_run: true
